server:
  port: 10001
spring:
  application:
    name: sharding-sphere-simple
  profiles:
    active: spfkfbgb # 根据需要切换
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql输出日志

